// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GhnbfAFMmWGv4fcE1veg_V0MAHxHy2k',
    appId: '1:523784049869:web:52678a0e0f0702831c0584',
    messagingSenderId: '523784049869',
    projectId: 'bloc-firestre-todo',
    authDomain: 'bloc-firestre-todo.firebaseapp.com',
    storageBucket: 'bloc-firestre-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGELvp7_6IQvUHbEWXNAq5wms4Koz3_I4',
    appId: '1:523784049869:android:53970fe6d83697a61c0584',
    messagingSenderId: '523784049869',
    projectId: 'bloc-firestre-todo',
    storageBucket: 'bloc-firestre-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvStaBibsS2rFI4Ke_dALDPlMnOiUn6Jw',
    appId: '1:523784049869:ios:46c52ac79526b2361c0584',
    messagingSenderId: '523784049869',
    projectId: 'bloc-firestre-todo',
    storageBucket: 'bloc-firestre-todo.appspot.com',
    iosBundleId: 'com.example.blocFirestroreTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvStaBibsS2rFI4Ke_dALDPlMnOiUn6Jw',
    appId: '1:523784049869:ios:6a09d666d530d4f11c0584',
    messagingSenderId: '523784049869',
    projectId: 'bloc-firestre-todo',
    storageBucket: 'bloc-firestre-todo.appspot.com',
    iosBundleId: 'com.example.blocFirestroreTodo.RunnerTests',
  );
}
